# Handle userland coredumps; this particular rule passes information about the
# coredump on to ucored(8) for handling.  ucored(8) will do some filtering
# depending on its configuration, and apply some conditional action.
notify 10 {
	match "system"          "kernel";
	match "subsystem"       "signal";
	match "type"            "coredump";
	action "/usr/local/libexec/ucore-shuttle -j $jid -P $ppid -p $pid -s $signo $comm $core";
};
